language: node_js
node_js:
  - "12.18.2"

branches:
  only:
    - main

before_script:
  - yarn install --frozen-lockfile

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: main
  local_dir: dist
